name: NASA APOD Twitter Bot

on:
  schedule:
    - cron: '35 9 * * *'  # Runs at 9:35 AM UTC daily
  workflow_dispatch:

jobs:
  post-apod:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd bots/nasa_apod
        pip install -r requirements.txt
    
    - name: Run bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      run: |
        cd bots/nasa_apod
        python bot.py